name: tsp-train-min
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda
  - timm
  - pyyaml
  - numpy
  - scipy
  - tqdm
  - matplotlib
  - seaborn
  - pandas
  - geopandas
  - tensorboard
  - torchmetrics